### ISSUE TITLE
Increased system load and Magic Mirror crash after 4 hours

### ISSUE THREAD

**Issue by Atrion** [sheyabernstein/MMM-pihole-stats#3]
On a Raspberry pi 3 with a fresh Raspbian install with Magic Mirror, Alexa Pi and Pi hole installed the system runs fine for the first 4 hours, than between the 4th and 5th hour the system load keeps increasing from the usual .5 up as high as 8.2, CPU temperature increased from low 50's to low 60's. Also the PiHole Magic mirror module (This) willl begin the disapear and reapear on the display till finally the system either freezes requiring reboot, or Magic Mirror Crashes needing a reboot to start again.

Upon removing This pi-hole module from my config the system has run fine for 2 days. I have repeated this problem serveral times.

**Comment by sheyabernstein** [comment]
Try setting `showSources` to `false` in your config. It sounds like the PiHole API can't handle too many consecutive requests.

**Comment by Atrion** [comment]
I have already tried that still resulted the same.

**Comment by brandongomez** [comment]
Same thing happened to me but I changed `showSources` to `false` and that did the trick. Been running stable ever since.

**Comment by topjor** [comment]
Reopening this because i know what the cause is.'

When showSources is enabled, for every time updateStats is run, scheduleUpdate is run twice, one in the retry clause for the main stats, once in the retry clause of the sources.
after a while, the browser will run out of memory and crash because of the number of xhr's that are scheduled / run.
I commented out the seccond scheduleUpdate for now

**Comment by pingywon** [comment]
I am having the same recurring issue. 

The module works fine but over the course of a few hours it chews up all the RAM because of spawned electron processes and then ultimately crashes out the MM.

I just relaunched with showSources to "false" and I will see if that cures it. 

If it does not - how/where can/do I change the scheduleUpdate?

**Comment by pingywon** [comment]
> Reopening this because i know what the cause is.'
> 
> When showSources is enabled, for every time updateStats is run, scheduleUpdate is run twice, one in the retry clause for the main stats, once in the retry clause of the sources.
> after a while, the browser will run out of memory and crash because of the number of xhr's that are scheduled / run.
> I commented out the seccond scheduleUpdate for now

My RAM usage was still climbing. I made this change and it SEEMS to have stabilized. Time will tell.

**Comment by dblanc28** [comment]
I have tried the previous mentioned fixes and I still seem to have this issue. i did discover some more information that may be useful in trouble shooting. i have magic mirror running on an RPI 3b with a monitor connected to it. I also have an ipad that just connects to that RPI with a web browser for a different mirror. i see requests to my pihole to get stats increase exponentially overtime until the magic mirror crashes. if i remove the ipad then the magic mirror only makes one request like it is supposed to. so why having the ipad in the mix causes an issue is the only part i dont know. what do you guys think?
